name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Publish slim to Registry
      uses: philopon/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/py3-rdkit
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: TINY=true
        tag_suffix: "-slim"

    - name: Publish full to Registry
      uses: philopon/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/py3-rdkit
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
