name: Publish Docker
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python_version: ["3.8", "3.7", "3.6", "3.5"]
                include:
                    - python_version: "3.8"
                      latest_python: true

        steps:
            - uses: actions/checkout@master

            - name: Publish slim to Registry
              uses: philopon/Publish-Docker-Github-Action@master
              with:
                  name: ${{ secrets.DOCKER_USERNAME }}/py3-rdkit
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  buildargs: TINY=true,PY_VERSION=${{ matrix.python_version }}
                  tag_names: true
                  tag_suffix: "-py${{ matrix.python_version }}-slim"

            - name: Publish full to Registry
              uses: philopon/Publish-Docker-Github-Action@master
              with:
                  name: ${{ secrets.DOCKER_USERNAME }}/py3-rdkit
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  buildargs: PY_VERSION=${{ matrix.python_version }}
                  tag_names: true
                  tag_suffix: "-py${{ matrix.python_version }}"

            - name: Publish latest to Registry
              if: matrix.latest_python
              uses: philopon/Publish-Docker-Github-Action@master
              with:
                  name: ${{ secrets.DOCKER_USERNAME }}/py3-rdkit
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  tag_names: true
